### ISSUE TITLE
SIGILL Error on some linux kernels [BUG]

### ISSUE THREAD

**Issue by alexdhill** [refresh-bio/NOMAD#2]
# Context
Operating system: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-67-generic x86_64)

# Expected Behavior
Downloading the precompiled binaries or building from source should yeild executables that print the usage when executed.

# Current Behavior 
Downloaded or built executables throw SIGILL [Illegal instruction: (core dumped)] when called. Nomad gives error 'cannot find version number for satc'.

I have downloaded the procompiled binaries and cloned the source to build nomad, and in both cases all the compiled executables (satc, satc_merge, satc_dump, etc.) throw SIGILL errors [Illegal instructions: (core dumped)].

I found that reducing the optimization levels from -O3 has successfully built most of the executables, but the satc_merge and sig_anch files still throw errors.

# Reproducing the issue
1. Launch VM using kernel version 5.15.0-67

2a. Git clone the NOMAD or R-NOMAD into the VM
-- or --
2b. Download the binaries into the VM

3. Enter VM and verify that the kernel is using Linux 5.15.0-67-generic x86_64 using ```uname -r```

4. Execute nomad or any of the executables.

# Potential Problem/Solution
However, I have recently tried running on another Ubuntu system (Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-60-generic x86_64)), and the files which cannot be run on my primary server are able to run with no issues.  It appears that with the kernel verion 5.15.0-60 NOMAD runs correctly, but on verion 5.15.0-67 it does not.

**Comment by marekkokot** [comment]
Hi,

thanks for reporting. It seems the problem is related to `-mavx` flag, at least on my Ubuntu VM removing this flag solves the issue.
Could you try this on your machine and let me know? 
I think we will need to remove this flag in the next release.
Could you also please give me the output of `lscpu` on your machine?

**Comment by marekkokot** [comment]
Great, thanks. We will need to test on our servers if it is relevant for performance, and if not, just remove this flag in the next release. Thank you again.
